configuration: Release
version: 1.0.{build}
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - java -version
  - choco install maven
  - mvn --version
  - SET PATH=C:\bin\apache-maven-3.2.3\bin;%PATH%
  - echo %PATH%
build_script:
  - mvn clean package -Dmaven.test.skip=true
test_script:
  - mvn test
only_commits:
  files:
    - lab 4/
